name: Proto Lint and Generate

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main, release/** ]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Install buf
        run: go install github.com/bufbuild/buf/cmd/buf@latest

      - name: Lint proto
        run: buf lint

      - name: Generate
        run: buf generate
